=== Deconstrained/deconstrained.github.io/resume.dtd
<!ELEMENT resume (personal,expertise,skills,certifications?,experience,education?,achievements*,projects*)>
<!ELEMENT personal (identity,strengths)>
<!ELEMENT expertise (area+)>
<!ELEMENT skills (skillset+)>
<!ELEMENT certifications (certification|certlogo)*>
<!ELEMENT experience (position+)>
<!ELEMENT education (degree+)>
<!ELEMENT achievements (achievement+)>
<!ELEMENT projects (project+)>


<!-- personal::children  -->
<!ELEMENT identity (fullname|contact|socialmedia)*>
<!ELEMENT strengths (point+)>

<!-- expertise::children -->
<!ELEMENT area CDATA>

<!-- skills::children -->
<!ELEMENT skillset (skill+)>

<!-- experience::children -->
<!ELEMENT position (dates+,title+,duty*,accomplishment*)>

<!-- achievements::children -->
<!ELEMENT achievement (title,brief)>
<!ATTLIST achievement %commonattr

<!-- projects::children -->
<!ELEMENT project (title,brief,point*)>

<!-- personal::contact::children -->
<!ELEMENT contact (phone|email|address|website)*)>
<!ELEMENT socialmedia (link*)>

<!-- Leaf node descriptors -->

<!ELEMENT accomplishment CDATA>
<!ELEMENT area CDATA>
<!ELEMENT brief CDATA>
<!ELEMENT certification EMPTY>
<!ELEMENT certlogo CDATA>
<!ELEMENT dates EMPTY>
<!ELEMENT degree EMPTY>
<!ELEMENT duty CDATA>
<!ELEMENT email CDATA>
<!ELEMENT fullname CDATA>
<!ELEMENT link CDATA>
<!ELEMENT phone CDATA>
<!ELEMENT point CDATA>
<!ELEMENT skill CDATA>
<!ELEMENT title CDATA>
<!ELEMENT website CDATA>


<!-- Parameter entity shortcuts: -->
<!ENTITY % title 'title CDATA #REQUIRED'>
<!ENTITY % type 'type CDATA #IMPLIED'>
<!ENTITY % cat 'cat CDATA #IMPLIED'><!-- To be used for categorizing content, i.e. for tailoring and displaying subsets of data --> 

<!-- Attribute declarations -->

<!-- <!ATTLIST accomplishment> -->
<!-- <!ATTLIST achievement> -->
<!-- <!ATTLIST brief> -->
<!-- <!ATTLIST certifications> -->
<!-- <!ATTLIST certlogo> -->
<!-- <!ATTLIST duty> -->
<!-- <!ATTLIST education> -->
<!-- <!ATTLIST experience> -->
<!-- <!ATTLIST expertise> -->
<!-- <!ATTLIST fullname> -->
<!-- <!ATTLIST personal> -->
<!-- <!ATTLIST point> -->
<!-- <!ATTLIST skill> -->
<!-- <!ATTLIST title> -->

<!ATTLIST achievements %type;>
<!ATTLIST area %cat;>
<!ATTLIST certification agency CDATA #REQUIRED %title; date CDATA #REQUIRED validuntil CDATA #IMPLIED>
<!ATTLIST dates start CDATA #REQUIRED end CDATA "present">
<!ATTLIST degree %title; major CDATA #REQUIRED institution CDATA #REQUIRED year CDATA #REQUIRED gpa CDATA #IMPLIED>
<!ATTLIST email %type;>
<!ATTLIST link site CDATA #REQUIRED>
<!ATTLIST phone %type;>
<!ATTLIST position location CDATA #IMPLIED pos CDATA #IMPLIED org CDATA #IMPLIED>
<!ATTLIST projects %type;>
<!ATTLIST skills %type;>
<!ATTLIST skillset %type; %cat;>
<!ATTLIST website href CDATA #REQUIRED>

=== Deconstrained/deconstrained.github.io/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/GenericTech.xsl"?>

<!DOCTYPE resume SYSTEM "resume.dtd">

<resume>

<personal>
    <identity>

        <fullname>Demitri A. Morgan</fullname>

        <contact>
            <phone type="Google voice">(831) 607-9833</phone>
            <email>demitri.morgan@gmail.com</email>
            <website href="http://demitrimorgan.com">demitrimorgan.com</website>
        </contact>

        <socialmedia>
            <link site="LinkedIn" href="https://www.linkedin.com/in/demitrimorgan">demitrimorgan</link>
            <link site="GitHub" href="https://github.com/Deconstrained">Deconstrained</link>
            <link site="Google+" href="https://plus.google.com/+DemitriMorgan/">+DemitriMorgan</link>
            <!-- <link site="Twitter" href="https://twitter.com/DemetriusArthur/">demetriusarthur</link> -->
            <link site="Facebook" href="https://www.facebook.com/demitri.morgan">demitri.morgan</link>
        </socialmedia>

    </identity>

    <strengths><!-- Type any and all strong points here, specify the specialization as a comma-delinated type attribute-->
        <point>Self-motivated individual with experience in rapid self-teaching</point>
        <point cat="IT,education">Ability to effectively communicate concepts of technical nature</point>
        <point cat="software">Experienced in both contributing to existing software/research projects and building them from scratch</point>
        <!-- <point cat="foodservice,bluecollar">Experienced and able to safely lift heavy objects and work with hazardous materials</point>
        <point cat="foodservice">Over a decade of combined prep cooking and dishwashing experience in both both a professional and personal setting.</point> -->
    </strengths>

</personal>

<expertise>
    <area cat="academic">Computational Physics</area>
    <area cat="software">Web Development</area>
    <!-- Reason: not an expertise but a skill, and Git is covered <area cat="software,academic">Version Control</area> -->
    <!-- <area cat="academic">MVC-based Design</area> -->
    <area cat="software">Test-driven Development</area>
    <area cat="IT">UNIX administration</area>
    <area cat="IT">Network Configuration</area>
    <area cat="IT">IT Troubleshooting</area>
    <area cat="IT">Datacenter Support</area>
    <area cat="academic">Tutoring</area>
</expertise>

<skills type="Technical">

    <skillset type="Language and Framework" cat="software">
        <skill>Python</skill>
        <skill>PHP</skill>
        <skill>MySQL</skill>
        <skill>Yii Framework</skill>
        <skill>JavaScript</skill>
        <skill>jQuery</skill>
        <skill>XML</skill>
        <skill>HTML5</skill>
        <skill>CSS3</skill>
        <skill>SASS</skill>
        <skill>Foundation</skill>
        <skill>WordPress</skill>
        <skill>C</skill>
        <skill>GNU Make</skill>
    </skillset>

    <skillset type="Scientific Computing and Research" cat="academic">
        <skill>Fortran 77/90</skill>
        <skill>OpenMPI</skill>
        <skill>IDL</skill>
        <skill>MatLab</skill>
        <skill>Mathematica</skill>
        <skill>NumPy</skill>
        <skill>MatPlotLib</skill>
        <skill>LaTeX</skill>
        <skill>Asymptote</skill>
    </skillset>

    <skillset type="Software" cat="IT,software,academic">
        <skill>Linux</skill>
        <skill>Apache</skill>
        <skill>Git</skill>
        <skill>AWS</skill>
        <skill>Vim</skill>
        <skill>Asterisk</skill>
    </skillset>

</skills>

<certifications>
    
    <certification agency="CompTIA" title="Network+" date="March 2015" validuntil="March 2018" />
    <certification agency="W3Schools" title="HTML" date="November 2014" />
    <certification agency="W3Schools" title="CSS" date="November 2014" />
    <certification agency="W3Schools" title="PHP" date="November 2014" />
    <certification agency="W3Schools" title="JavaScript" date="November 2014" />
    <certification agency="W3Schools" title="jQuery" date="November 2014" />
    <certification agency="W3Schools" title="XML" date="November 2014" />

    <certlogo>
        <a href="http://www.refsnesdata.no/certification/w3certified.asp?email=demitri.morgan@gmail.com"><img src="img/w3cert.png" style="border:0" alt="W3Schools" /></a>
    </certlogo>

    <certlogo>
        <img src="img/NetworkPlus_Certified_CE_Logo.png" alt="CompTIA Network+ CE" />
    </certlogo>

</certifications>

<experience>

    <position pos="at" org="Hurricane Electric LLC"  location="Fremont, CA" href="http://he.net/">
        <dates start="October 2014" end="present" />
        <title>Support Engineer</title>
        <duty>Customer authentication and colocation security</duty>
        <duty>Hardware installation</duty>
        <duty>Cable management</duty>
        <duty>Hands-on data center support</duty>
        <duty>Network, email and web hosting troubleshooting</duty>
        <accomplishment>(in progress; nearly finished) Fully automated the process of detecting and notifying customers of vulnerable/out of date web application software in their hosting accounts</accomplishment>
    </position>

    <position pos="at" org="X2Engine Inc." location="Santa Cruz, CA" href="http://www.x2engine.com/">
        <dates start="January 2012" end="July 2014" />
        <title>Software Engineer</title>
        <title>Systems Administrator</title>
        <duty>Configuring and maintaining company IT systems</duty>
        <duty>Development of core software components and services</duty>
        <duty>Documentation authoring</duty>
        <accomplishment>Created multiple automated systems for deploying the product as a service on-demand in LAMP environments.</accomplishment>
        <accomplishment>Introduced numerous best practices to the project, including unit testing with PHPUnit and software documentation with JavaDoc-style comments.</accomplishment>
        <accomplishment>Redesigned the software update process, improving its overall efficiency and stability, reducing the time to release a new version by as much as 80%, and giving it the ability to support multiple products.</accomplishment>
        <accomplishment>Trained four other staff engineers.</accomplishment>
        <accomplishment>Designed and built a REST-ful JSON API compatible with Zapier.</accomplishment>
        <accomplishment>Developed server monitoring and status alert programs</accomplishment>
        <accomplishment>Created the X2Planet license key and software registration service.</accomplishment>
        <accomplishment>Authored extensive and detailed documentation using MediaWiki - see wiki.x2engine.com</accomplishment>
        <accomplishment>Installed, configured and administered the company's Asterisk-based VoIP phone system and numerous other internal-use software components, scripts, networks, web applications, services and systems.</accomplishment>
        <accomplishment>Assisted and solved problems for customers and end users.</accomplishment>
    </position>

    <position pos="with" org="University Space Research Association" location="Mountain View, CA" href="http://www.usra.edu/">
        <dates start="July 2009" end="December 2011" />
        <title>Research Associate at NASA Ames Research Center</title>
        <duty>Working with professors on astrophysical research pertaining to the formation of planetary systems and rings.</duty>
        <accomplishment>Listed as co-author of P. R. Estrada <em>et al.,</em> Icarus <strong>252</strong> (2015) 415–439</accomplishment>
        <accomplishment>Isolated and re-purposed components of the Gadget-2 N-Body simulation for use in the planetary accretion problem.</accomplishment>
        <accomplishment>Created Python-based data parsing, reduction and visualization tools for output from multithreaded simulations.</accomplishment>
        <accomplishment>Designed and implemented strategies for retrofitting single-CPU astrophysical simulations for running in parallel using OpenMPI.</accomplishment>
        <accomplishment>Created load optimization algorithms for parallel scientific computing.</accomplishment>
        <accomplishment>Introduced the practice of using version control and GNU Make, and instructed collaborators in their use.</accomplishment>
        <accomplishment>Authored extensive documentation using DoxyGen</accomplishment>
    </position>

    <position pos="for" org="Life Lab Science Program" location="Santa Cruz, CA" href="http://www.lifelab.org/">
        <dates start="January 2008" end="November 2010" />
        <title>Web Development Consultant</title>
        <duty>WordPress theme development</duty>
        <duty>Performing website management and administration tasks</duty>

        <accomplishment>Migrated a static 30+ page HTML website into a dynamic website managed by WordPress.</accomplishment>
        <accomplishment>Wrote parsing tools with regular expressions to assist in automatic migration.</accomplishment>
    </position>

    <position pos="at" org="Aptos Learning Center" location="Aptos, CA">
        <dates start="August 2008" end="September 2009" />
        <title>Tutor</title>
        <duty>Mathematics, logic, analytical thinking and English syntax tutoring of students grade 5-11 with learning differences</duty>
        <duty>Creating and implementing supplemental teaching aides for instruction in arithmetic</duty>
        <duty>Implementing the On Cloud Nine(tm) Teaching System</duty>
    </position>

    <position pos="with" org="Merit Educational Consultants LLC" location="Soquel, CA" href="http://www.meritworld.com/">
        <dates start="August 2008" end="July 2009" />
        <title>Tutor</title>
        <duty>Tutoring/instruction in web design</duty>
        <duty>Development and editing of physics laboratory curricula</duty>
        <duty>Mathematics (SAT/College prep) tutoring</duty>
    </position>
